version: '3'
services:
  db:
    image: mysql:8
    container_name: db
    ports:
      - '3312:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sistema_podologia
      MYSQL_USER: pi-senac-user
      MYSQL_PASSWORD: 'pi-senac'
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - pi-senac-network
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/pi-senac
    command: bash -c "yarn && yarn start:dev"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - DB_NAME=sistema_podologia
      - DB_USER=root
      - DB_PASSWORD='rootpassword'
      - DB_PORT='3306'
    volumes:
      - .:/usr/src/pi-senac
    ports:
      - '5050:3000'
      - '9222:9222'
    links:
      - db
    depends_on:
      - db
    networks:
      - pi-senac-network
networks:
  pi-senac-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
